// <auto-generated />
using System;
using EventParkingSystemApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventParkingSystemApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventParkingSystemApi.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("EventId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.BookingSeat", b =>
                {
                    b.Property<int>("BookingSeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingSeatId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtBooking")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.HasKey("BookingSeatId");

                    b.HasIndex("BookingId");

                    b.HasIndex("SeatId")
                        .IsUnique();

                    b.ToTable("BookingSeats");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@eventparking.com",
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "PLACEHOLDER_NOT_A_VALID_HASH_REGISTER_VIA_API",
                            Phone = "0000000000",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CustomerId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nila@example.com",
                            FullName = "Nila Kumar",
                            IsActive = true,
                            PasswordHash = "PLACEHOLDER_NOT_A_VALID_HASH_REGISTER_VIA_API",
                            Phone = "9876500001",
                            Role = "Customer",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EventTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ParkingFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A night of live music under the stars.",
                            EventDate = new DateOnly(2026, 12, 20),
                            EventTime = new TimeOnly(19, 0, 0),
                            IsLocked = false,
                            Name = "Sunburn Live 2026",
                            ParkingFee = 100.00m,
                            TicketPrice = 1500.00m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VenueId = 1
                        });
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.EventCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EventCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Concert"
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sports"
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Conference"
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Workshop"
                        });
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationId");

                    b.HasIndex("CustomerId", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.ParkingReservation", b =>
                {
                    b.Property<int>("ParkingReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParkingReservationId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("FeeAtBooking")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ParkingSlotId")
                        .HasColumnType("int");

                    b.HasKey("ParkingReservationId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("ParkingSlotId")
                        .IsUnique();

                    b.ToTable("ParkingReservations");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.ParkingSlot", b =>
                {
                    b.Property<int>("ParkingSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParkingSlotId"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("SlotLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParkingSlotId");

                    b.HasIndex("EventId", "SlotLabel")
                        .IsUnique();

                    b.ToTable("ParkingSlots");

                    b.HasData(
                        new
                        {
                            ParkingSlotId = 1,
                            EventId = 1,
                            SlotLabel = "P1",
                            Status = "Available"
                        },
                        new
                        {
                            ParkingSlotId = 2,
                            EventId = 1,
                            SlotLabel = "P2",
                            Status = "Available"
                        },
                        new
                        {
                            ParkingSlotId = 3,
                            EventId = 1,
                            SlotLabel = "P3",
                            Status = "Available"
                        },
                        new
                        {
                            ParkingSlotId = 4,
                            EventId = 1,
                            SlotLabel = "P4",
                            Status = "Available"
                        },
                        new
                        {
                            ParkingSlotId = 5,
                            EventId = 1,
                            SlotLabel = "P5",
                            Status = "Available"
                        },
                        new
                        {
                            ParkingSlotId = 6,
                            EventId = 1,
                            SlotLabel = "P6",
                            Status = "Available"
                        },
                        new
                        {
                            ParkingSlotId = 7,
                            EventId = 1,
                            SlotLabel = "P7",
                            Status = "Available"
                        },
                        new
                        {
                            ParkingSlotId = 8,
                            EventId = 1,
                            SlotLabel = "P8",
                            Status = "Available"
                        },
                        new
                        {
                            ParkingSlotId = 9,
                            EventId = 1,
                            SlotLabel = "P9",
                            Status = "Available"
                        },
                        new
                        {
                            ParkingSlotId = 10,
                            EventId = 1,
                            SlotLabel = "P10",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<string>("SeatRow")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeatId");

                    b.HasIndex("EventId", "SeatRow", "SeatNumber")
                        .IsUnique();

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatId = 1,
                            EventId = 1,
                            SeatNumber = 1,
                            SeatRow = "A",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 2,
                            EventId = 1,
                            SeatNumber = 2,
                            SeatRow = "A",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 3,
                            EventId = 1,
                            SeatNumber = 3,
                            SeatRow = "A",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 4,
                            EventId = 1,
                            SeatNumber = 4,
                            SeatRow = "A",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 5,
                            EventId = 1,
                            SeatNumber = 5,
                            SeatRow = "A",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 6,
                            EventId = 1,
                            SeatNumber = 6,
                            SeatRow = "A",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 7,
                            EventId = 1,
                            SeatNumber = 7,
                            SeatRow = "A",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 8,
                            EventId = 1,
                            SeatNumber = 8,
                            SeatRow = "A",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 9,
                            EventId = 1,
                            SeatNumber = 9,
                            SeatRow = "A",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 10,
                            EventId = 1,
                            SeatNumber = 10,
                            SeatRow = "A",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 11,
                            EventId = 1,
                            SeatNumber = 1,
                            SeatRow = "B",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 12,
                            EventId = 1,
                            SeatNumber = 2,
                            SeatRow = "B",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 13,
                            EventId = 1,
                            SeatNumber = 3,
                            SeatRow = "B",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 14,
                            EventId = 1,
                            SeatNumber = 4,
                            SeatRow = "B",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 15,
                            EventId = 1,
                            SeatNumber = 5,
                            SeatRow = "B",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 16,
                            EventId = 1,
                            SeatNumber = 6,
                            SeatRow = "B",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 17,
                            EventId = 1,
                            SeatNumber = 7,
                            SeatRow = "B",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 18,
                            EventId = 1,
                            SeatNumber = 8,
                            SeatRow = "B",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 19,
                            EventId = 1,
                            SeatNumber = 9,
                            SeatRow = "B",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 20,
                            EventId = 1,
                            SeatNumber = 10,
                            SeatRow = "B",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 21,
                            EventId = 1,
                            SeatNumber = 1,
                            SeatRow = "C",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 22,
                            EventId = 1,
                            SeatNumber = 2,
                            SeatRow = "C",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 23,
                            EventId = 1,
                            SeatNumber = 3,
                            SeatRow = "C",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 24,
                            EventId = 1,
                            SeatNumber = 4,
                            SeatRow = "C",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 25,
                            EventId = 1,
                            SeatNumber = 5,
                            SeatRow = "C",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 26,
                            EventId = 1,
                            SeatNumber = 6,
                            SeatRow = "C",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 27,
                            EventId = 1,
                            SeatNumber = 7,
                            SeatRow = "C",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 28,
                            EventId = 1,
                            SeatNumber = 8,
                            SeatRow = "C",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 29,
                            EventId = 1,
                            SeatNumber = 9,
                            SeatRow = "C",
                            Status = "Available"
                        },
                        new
                        {
                            SeatId = 30,
                            EventId = 1,
                            SeatNumber = 10,
                            SeatRow = "C",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("VenueId");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            Address = "12 Beach Road, Chennai",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Marina Grand Arena",
                            TotalCapacity = 500,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.Booking", b =>
                {
                    b.HasOne("EventParkingSystemApi.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventParkingSystemApi.Models.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.BookingSeat", b =>
                {
                    b.HasOne("EventParkingSystemApi.Models.Booking", "Booking")
                        .WithMany("BookingSeats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventParkingSystemApi.Models.Seat", "Seat")
                        .WithOne("BookingSeat")
                        .HasForeignKey("EventParkingSystemApi.Models.BookingSeat", "SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.Event", b =>
                {
                    b.HasOne("EventParkingSystemApi.Models.EventCategory", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventParkingSystemApi.Models.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.Notification", b =>
                {
                    b.HasOne("EventParkingSystemApi.Models.Customer", "Customer")
                        .WithMany("Notifications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.ParkingReservation", b =>
                {
                    b.HasOne("EventParkingSystemApi.Models.Booking", "Booking")
                        .WithOne("ParkingReservation")
                        .HasForeignKey("EventParkingSystemApi.Models.ParkingReservation", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventParkingSystemApi.Models.ParkingSlot", "ParkingSlot")
                        .WithOne("ParkingReservation")
                        .HasForeignKey("EventParkingSystemApi.Models.ParkingReservation", "ParkingSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ParkingSlot");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.ParkingSlot", b =>
                {
                    b.HasOne("EventParkingSystemApi.Models.Event", "Event")
                        .WithMany("ParkingSlots")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.Payment", b =>
                {
                    b.HasOne("EventParkingSystemApi.Models.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("EventParkingSystemApi.Models.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.Seat", b =>
                {
                    b.HasOne("EventParkingSystemApi.Models.Event", "Event")
                        .WithMany("Seats")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.Booking", b =>
                {
                    b.Navigation("BookingSeats");

                    b.Navigation("ParkingReservation");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.Customer", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.Event", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ParkingSlots");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.EventCategory", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.ParkingSlot", b =>
                {
                    b.Navigation("ParkingReservation");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.Seat", b =>
                {
                    b.Navigation("BookingSeat");
                });

            modelBuilder.Entity("EventParkingSystemApi.Models.Venue", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
